# Generated by Django 4.1.7 on 2023-02-19 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload_image', '0004_remove_image_owner_image_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('thumb_200', models.ImageField(upload_to='thumbs')),
                ('thumb_400', models.ImageField(upload_to='thumbs')),
                ('thumb_original', models.ImageField(upload_to='thumbs')),
            ],
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
    ]
