# Generated by Django 4.1.7 on 2023-02-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_image', '0006_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
